### ISSUE TITLE
Will not allow '>' at the end of any cfml tags

### ISSUE THREAD

**Issue by Yamaha32088** [jcberquist/sublimetext-cfml#34] opened 2016-07-29 15:36 UTC
Another developer and I noticed that when we try to type something like `<cfset foo="bar">` the closing `>` will not be printed. It is like the key is disabled. We were on the most recent branch as well using the latest version of Sublime.

**Comment by jcberquist** [comment] 2016-07-29 15:51
Can you verify that you are using this package and not https://github.com/SublimeText/ColdFusion? 

I know this issue has occured with `SublimeText/ColdFusion` (e.g. https://github.com/SublimeText/ColdFusion/issues/106)

If you are using this package, and you have `SublimeText/ColdFusion` installed as well, can you please add `ColdFusion` to your `ignored_packages` user setting, restart Sublime Text, and see if the problem persists?

I can't reproduce it with just this plugin. If it still happens after disabling `SublimeText/ColdFusion`, could you please provide a minimal file string in a fenced code block where the error occurs for you? For example:
```
<html>
<cfset foo="bar"
</html>
```

**Comment by Yamaha32088** [comment] 2016-07-29 16:24
We did have that package installed. I get the same thing after disabling all packages and removing them from the Packages directory. I have tried both CFC and CFML but get the same results with a brand new file and where the only line is  `<cfset foo="bar">` the tag does not print. I tried some of the troubleshooting steps in the issue that you referenced and when I turn on debugging it says 
> cfml_auto_insert_closing_tag

So it seems to be trying to run the function correctly but just not outputting anything.

**Comment by jcberquist** [comment] 2016-07-29 17:30
I assume after running `sublime.log_commands(True)`  and pressing <kbd>></kbd>, when you see `cfml_auto_insert_closing_tag` printed to the console, that it is the only thing printed to the console? I am not really sure what is going on at this point, so here are some general questions.

- What OS and what version of ST do you have? 
- Did you install this package with Package Control, or via download/git clone? 
- If you go to `preferences` -> `Browse Packages`, is it contained in a folder in that directory?
- Are you sure you entirely removed `SublimeText/ColdFusion`? You say you "tried both CFC and CFML" but `CFC` should not be an option for you in your syntaxes if the `SublimeText/ColdFusion` package has     been removed. 
- Have you looked in your `User` folder (under Packages) for any key-binding files? If you have any, could you check for any key-bindings to the <kbd>></kbd> key?
- Is it possible for you to try this on a clean install of ST3 (possibly a portable version) with just `Package Control` and `CFML` to see if this issue happens then?

**Comment by Shult2** [comment] 2016-08-09 13:54
![cfcommand](https://cloud.githubusercontent.com/assets/19411735/17518759/ca2442e8-5e0e-11e6-83b7-f520527c4e42.PNG)
![closingtag](https://cloud.githubusercontent.com/assets/19411735/17518768/d092319e-5e0e-11e6-8aa4-105c76a6e415.PNG)

**Comment by Shult2** [comment] 2016-08-09 14:09
And I also cannot add a "/" to close a tag set. It says "command: close_cfml_tag" in the console. 
![forwardslash](https://cloud.githubusercontent.com/assets/19411735/17519314/02f67c7e-5e11-11e6-9254-94c5f3036a40.PNG)

**Comment by jcberquist** [comment] 2016-08-09 14:38
If you close and then open Sublime Text, then open the console, do you see any import errors? I think I may have hard coded a path in the package which could be the source of this problem.

**Comment by Shult2** [comment] 2016-08-09 20:37
Yes, it says, "ImportError: No module named 'CFML'"

**Comment by jcberquist** [comment] 2016-08-10 00:50
@Shult2: Thanks, I have removed the hard coded import paths, it should hopefully fix the issue you are seeing.
@Yamaha32088: If you installed the package manually in a folder with a name other than `CFML` it is likely that your issue had the same cause. If so, please download the latest master and try it out.

**Comment by Shult2** [comment] 2016-08-10 13:26
Appears to be working. You rock!

**Comment by jcberquist** [comment] 2016-08-11 02:03
@Shult2: Thanks for confirming. 

@Yamaha32088: I am going to close this, as https://github.com/jcberquist/sublimetext-cfml/commit/42cfa3332cbd4c5c9c9cfc53cca39fd3eb523b7f does fix an issue that was causing behavior similar to what you described. If after trying the latest master this is still an issue for you please let me know.

**Closed by jcberquist** 2016-08-11 02:03 UTC

**Comment by vm-jade** [comment] 2016-10-04 23:57
Hi, I still seem to be having the problem described here (unable to type ">" or "/"). The console outputs the same commands as Shult2, except no "ImportError" appears upon load (I'm using Mac OS).

CFML package: v0.16.0
Sublime: Stable channel, build 3126
OS X El Capitan 10.11.3

The comment in [42cfa33](https://github.com/jcberquist/sublimetext-cfml/commit/42cfa3332cbd4c5c9c9cfc53cca39fd3eb523b7f) hints at having a folder named "CFML"—is it possible this still doesn't work for OS X which only has an "Installed Packages" folder?

**Comment by jcberquist** [comment] 2016-10-05 01:59
Hi, as a starting point for debugging this, could you take a look at the questions here:  https://github.com/jcberquist/sublimetext-cfml/issues/42#issuecomment-241166184?

You have already given the plugin version, and you indicate that the commands are logged to the console. So it would be helpful to know to if you installed the plugin via package control, and if you have ever installed it manually or not.

**Comment by vm-jade** [comment] 2016-10-05 04:04
Hi, this seems to be working for me now after a second reboot—apologies for the false alarm (I was using package control only). Thanks for the reply. and for the great sublime package :)
